"""Generate the dependency licence register and fail on licence-policy violations.

Reads uv.lock and pnpm-lock.yaml for the dependency list and resolves each licence from
LOCAL data only: installed distribution metadata in the uv venv, and package.json files in
node_modules/.pnpm. No network calls. A licence that cannot be resolved is reported UNKNOWN
and fails the check; it is never defaulted to permissive.

Outputs:
  docs/licenses.md                 full register (name, version, licence, scope, note)
  docs/adr/0002-stack-pins.md      generated block between the licences-register markers

Usage:
    python scripts/licenses_report.py          # regenerate both files, exit 1 on violations
    python scripts/licenses_report.py --check  # regenerate in memory; fail on diff or violation

Policy (PRP-00 Clarification 10): permissive licences pass; MPL-2.0 passes for dev-only
packages; copyleft, non-commercial and EULA licences fail unless the package is on ALLOWLIST
with a reason. DENYLIST entries always fail (ADR-0002: @cosmograph is CC-BY-NC).

Platform-gated packages that are not installed on this machine (for example rolldown
bindings for another OS) cannot be read locally; their licence is carried forward from the
committed docs/licenses.md for the SAME name and version, and is UNKNOWN if there is no such
row. CI installs every architecture, so it never relies on the carry-forward.
"""

from __future__ import annotations

import argparse
import fnmatch
import json
import re
import sys
import tomllib
from dataclasses import dataclass
from importlib import metadata
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")  # type: ignore[union-attr]

ROOT = Path(__file__).resolve().parents[1]

# --- policy -----------------------------------------------------------------------------

PERMISSIVE = {
    "MIT",
    "MIT-0",
    "BSD",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "0BSD",
    "Apache-2.0",
    "ISC",
    "PSF-2.0",
    "Python-2.0",
    "Unlicense",
    "CC0-1.0",
    "Zlib",
    "BlueOak-1.0.0",
    "CC-BY-4.0",
}
# Weak (file-level) copyleft: allowed only when the package is dev-only.
DEV_ONLY_OK = {"MPL-2.0"}

# name -> reason. Only for non-permissive licences; never applies to UNKNOWN.
ALLOWLIST: dict[str, str] = {}
# glob patterns that always fail, whatever licence metadata says.
DENYLIST: dict[str, str] = {
    "@cosmograph/*": "CC-BY-NC (non-commercial); forbidden by ADR-0002",
}

ALIASES = {
    "mit license": "MIT",
    "the mit license": "MIT",
    "mit": "MIT",
    "apache software license": "Apache-2.0",
    "apache license 2.0": "Apache-2.0",
    "apache license, version 2.0": "Apache-2.0",
    "apache 2.0": "Apache-2.0",
    "apache-2.0": "Apache-2.0",
    "bsd license": "BSD",
    "bsd": "BSD",
    "new bsd license": "BSD-3-Clause",
    "bsd 3-clause": "BSD-3-Clause",
    "isc license": "ISC",
    "isc license (iscl)": "ISC",
    "python software foundation license": "PSF-2.0",
    "psf": "PSF-2.0",
    "psfl": "PSF-2.0",
    "mozilla public license 2.0 (mpl 2.0)": "MPL-2.0",
    "mpl-2.0": "MPL-2.0",
}
CLASSIFIER_MAP = {
    "License :: OSI Approved :: MIT License": "MIT",
    "License :: OSI Approved :: Apache Software License": "Apache-2.0",
    "License :: OSI Approved :: BSD License": "BSD",
    "License :: OSI Approved :: ISC License (ISCL)": "ISC",
    "License :: OSI Approved :: Python Software Foundation License": "PSF-2.0",
    "License :: OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)": "MPL-2.0",
    "License :: OSI Approved :: The Unlicense (Unlicense)": "Unlicense",
}

UNKNOWN = "UNKNOWN"
FIRST_PARTY = "first-party"

# Hand-recorded support notes for packages where the project has a fact worth keeping.
# Everything else gets a note derived only from the version string.
SUPPORT_NOTES: dict[str, str] = {
    "typescript": "pinned 6.0.x; TS 7 incompatible with typescript-eslint (ADR-0002)",
    "hypothesis": "dev-only: MPL-2.0 is file-level copyleft (ADR-0002)",
}

ADR_PATH = ROOT / "docs" / "adr" / "0002-stack-pins.md"
BEGIN = "<!-- BEGIN licences-register (generated by scripts/licenses_report.py) -->"
END = "<!-- END licences-register -->"

# --- data model -------------------------------------------------------------------------


@dataclass(frozen=True)
class Dep:
    ecosystem: str  # "python" or "npm"
    name: str
    version: str
    licence: str  # normalised display string, or UNKNOWN, or first-party
    dev_only: bool
    note: str

    @property
    def scope(self) -> str:
        if self.licence == FIRST_PARTY:
            return "first-party"
        return "dev-only" if self.dev_only else "runtime"


# --- licence classification -------------------------------------------------------------

_TOKEN = re.compile(r"\(|\)|[^\s()]+")


def _canon(licence_id: str) -> str:
    return ALIASES.get(licence_id.lower(), licence_id)


def normalise_text(raw: str | None) -> str | None:
    """Map free text to an SPDX-style expression, or None when it is not usable."""
    if raw is None:
        return None
    text = " ".join(raw.split())
    if not text or text.upper() in {"UNKNOWN", "NONE", "N/A"} or len(text) > 120:
        return None
    if text.lower().startswith("see license"):
        return None
    alias = ALIASES.get(text.lower())
    return alias if alias else text


def _rank(licence_id: str, dev_only: bool) -> int:
    """0 ok, 1 not ok. Unrecognised ids are flagged, never assumed permissive."""
    if licence_id in PERMISSIVE:
        return 0
    if licence_id in DEV_ONLY_OK and dev_only:
        return 0
    return 1


def expression_ok(expr: str, dev_only: bool) -> bool:
    """Evaluate an SPDX expression: OR needs one acceptable branch, AND needs all."""
    tokens = _TOKEN.findall(expr)
    pos = 0

    def peek() -> str | None:
        return tokens[pos] if pos < len(tokens) else None

    def parse_or() -> bool:
        nonlocal pos
        result = parse_and()
        while (peek() or "").upper() == "OR":
            pos += 1
            right = parse_and()
            result = result or right
        return result

    def parse_and() -> bool:
        nonlocal pos
        result = parse_atom()
        while (peek() or "").upper() == "AND":
            pos += 1
            right = parse_atom()
            result = result and right
        return result

    def parse_atom() -> bool:
        nonlocal pos
        tok = peek()
        if tok is None:
            return False
        pos += 1
        if tok == "(":
            inner = parse_or()
            if peek() == ")":
                pos += 1
            return inner
        ok = _rank(_canon(tok), dev_only) == 0
        if (peek() or "").upper() == "WITH":  # exception clause: judged on the base licence
            pos += 2
        return ok

    return parse_or()


def deny_reason(name: str) -> str | None:
    for pattern, reason in DENYLIST.items():
        if fnmatch.fnmatchcase(name, pattern):
            return reason
    return None


def violation(dep: Dep) -> str | None:
    """Return why the dependency fails policy, or None when it passes."""
    denied = deny_reason(dep.name)
    if denied:
        return f"denied: {denied}"
    if dep.licence == FIRST_PARTY:
        return None
    if dep.licence == UNKNOWN:
        return "licence UNKNOWN (no local metadata; never defaulted to permissive)"
    if expression_ok(dep.licence, dep.dev_only):
        return None
    if dep.name in ALLOWLIST:
        return None
    where = "dev-only" if dep.dev_only else "runtime"
    return f"non-permissive licence '{dep.licence}' ({where}) and not on the allowlist"


# --- Python (uv.lock + installed metadata) ----------------------------------------------


def _pep503(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def find_site_packages(venv: Path) -> list[Path]:
    return sorted(p for p in venv.glob("**/site-packages") if p.is_dir())


def python_licence(dist: metadata.Distribution) -> str:
    meta = dist.metadata
    expr = normalise_text(meta.get("License-Expression"))
    if expr:
        return expr
    legacy = normalise_text(meta.get("License"))
    if legacy:
        return legacy
    found = sorted(
        {CLASSIFIER_MAP[c] for c in meta.get_all("Classifier") or [] if c in CLASSIFIER_MAP}
    )
    if found:
        return " OR ".join(found) if len(found) > 1 else found[0]
    return UNKNOWN


def version_note(name: str, version: str) -> str:
    if name in SUPPORT_NOTES:
        return SUPPORT_NOTES[name]
    if re.search(r"(a|b|rc|alpha|beta|dev)\.?\d*$|-", version):
        return "pre-release version; no support window recorded"
    if re.match(r"0\.", version):
        return "0.x: minor releases may break; no support window recorded"
    return "no EOL published locally; Dependabot tracks releases"


def read_uv_lock(
    lock: Path, site_dirs: list[Path], carried: dict[tuple[str, str, str], str]
) -> list[Dep]:
    data = tomllib.loads(lock.read_text(encoding="utf-8"))
    packages = data.get("package", [])
    by_name = {_pep503(p["name"]): p for p in packages}

    members = {
        _pep503(p["name"])
        for p in packages
        if set(p.get("source", {})) & {"editable", "virtual", "directory"}
    }
    # Runtime closure: dependencies (and optional extras) of workspace members, not their
    # dev groups. Anything else in the lock is only reachable through dev tooling.
    runtime: set[str] = set()
    stack = [
        _pep503(d["name"])
        for m in members
        for d in by_name[m].get("dependencies", [])
        + [e for ex in by_name[m].get("optional-dependencies", {}).values() for e in ex]
    ]
    while stack:
        n = stack.pop()
        if n in runtime or n not in by_name:
            continue
        runtime.add(n)
        stack.extend(_pep503(d["name"]) for d in by_name[n].get("dependencies", []))

    installed = {
        _pep503(d.metadata["Name"]): d
        for d in metadata.distributions(path=[str(s) for s in site_dirs])
        if d.metadata["Name"]
    }
    deps: list[Dep] = []
    for pkg in packages:
        name, version = pkg["name"], pkg.get("version", "")
        key = _pep503(name)
        if key in members:
            deps.append(Dep("python", name, version, FIRST_PARTY, False, "workspace member"))
            continue
        dist = installed.get(key)
        if dist is not None and dist.version == version:
            lic = python_licence(dist)
        else:
            lic = carried.get(("python", name, version), UNKNOWN)
        deps.append(
            Dep("python", name, version, lic, key not in runtime, version_note(name, version))
        )
    return deps


# --- npm (pnpm-lock.yaml + node_modules/.pnpm) ------------------------------------------


def _unquote(text: str) -> str:
    text = text.strip()
    if len(text) >= 2 and text[0] == text[-1] and text[0] in "'\"":
        return text[1:-1]
    return text


def _split_key(key: str) -> tuple[str, str]:
    key = key.split("(", 1)[0]
    name, _, version = key.rpartition("@")
    return name, version


def parse_pnpm_lock(text: str) -> tuple[list[tuple[str, str]], set[str]]:
    """Return ([(name, version)] for every package, runtime-reachable base keys)."""
    section = ""
    packages: list[tuple[str, str]] = []
    snap_edges: dict[str, list[str]] = {}
    roots: list[str] = []
    cur_key = ""
    sub = ""
    imp_dev = False
    imp_name = ""
    for line in text.splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        indent = len(line) - len(line.lstrip(" "))
        body = line.strip()
        if indent == 0:
            section = body.rstrip(":")
            continue
        if section == "packages" and indent == 2 and body.endswith(":"):
            packages.append(_split_key(_unquote(body[:-1])))
        elif section == "snapshots":
            if indent == 2 and body.endswith(":"):
                cur_key = _unquote(body[:-1])
                snap_edges.setdefault(cur_key, [])
            elif indent == 2 and body.endswith(": {}"):
                snap_edges.setdefault(_unquote(body[: -len(": {}")]), [])
            elif indent == 4:
                sub = body.rstrip(":")
            elif indent == 6 and sub in {"dependencies", "optionalDependencies"}:
                dep, _, val = body.partition(": ")
                snap_edges[cur_key].append(f"{_unquote(dep)}@{_unquote(val)}")
        elif section == "importers":
            if indent == 4:
                sub = body.rstrip(":")
                imp_dev = sub == "devDependencies"
            elif indent == 6 and sub in {"dependencies", "devDependencies", "optionalDependencies"}:
                imp_name = _unquote(body.rstrip(":"))
            elif indent == 8 and body.startswith("version:") and not imp_dev:
                version = _unquote(body.split(":", 1)[1])
                if not version.startswith("link:"):
                    roots.append(f"{imp_name}@{version}")
    runtime: set[str] = set()
    stack = list(roots)
    while stack:
        key = stack.pop()
        if key in runtime:
            continue
        runtime.add(key)
        stack.extend(snap_edges.get(key, []))
    return packages, {_split_key(k)[0] + "@" + _split_key(k)[1] for k in runtime}


def npm_licence(pkg: dict) -> str:
    raw = pkg.get("license")
    if isinstance(raw, dict):
        raw = raw.get("type")
    if raw is None and isinstance(pkg.get("licenses"), list):
        types = [str(x["type"]) for x in pkg["licenses"] if isinstance(x, dict) and x.get("type")]
        raw = " OR ".join(types) if types else None
    if not isinstance(raw, str):
        return UNKNOWN
    return normalise_text(raw) or UNKNOWN


def index_node_modules(pnpm_dir: Path) -> dict[tuple[str, str], dict]:
    """Map (name, version) -> package.json for every package under node_modules/.pnpm."""
    index: dict[tuple[str, str], dict] = {}
    if not pnpm_dir.is_dir():
        return index

    def load(pkg_dir: Path) -> None:
        manifest = pkg_dir / "package.json"
        try:
            pkg = json.loads(manifest.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            return
        name, version = pkg.get("name"), pkg.get("version")
        if isinstance(name, str) and isinstance(version, str):
            index.setdefault((name, version), pkg)

    for store in sorted(pnpm_dir.iterdir()):
        modules = store / "node_modules"
        if not modules.is_dir():
            continue
        for entry in modules.iterdir():
            if entry.name.startswith("@"):
                for child in entry.iterdir():
                    load(child)
            else:
                load(entry)
    return index


def read_pnpm_lock(
    lock: Path, pnpm_dir: Path, carried: dict[tuple[str, str, str], str]
) -> list[Dep]:
    packages, runtime = parse_pnpm_lock(lock.read_text(encoding="utf-8"))
    index = index_node_modules(pnpm_dir)
    deps: list[Dep] = []
    for name, version in packages:
        pkg = index.get((name, version))
        lic = npm_licence(pkg) if pkg else carried.get(("npm", name, version), UNKNOWN)
        deps.append(
            Dep(
                "npm",
                name,
                version,
                lic,
                f"{name}@{version}" not in runtime,
                version_note(name, version),
            )
        )
    return deps


# --- rendering --------------------------------------------------------------------------


def parse_register(text: str) -> dict[tuple[str, str, str], str]:
    """Read (ecosystem, name, version) -> licence from a previously generated register."""
    out: dict[tuple[str, str, str], str] = {}
    eco = ""
    for line in text.splitlines():
        if line.startswith("## Python"):
            eco = "python"
        elif line.startswith("## npm"):
            eco = "npm"
        elif eco and line.startswith("| ") and not line.startswith(("| Package", "| ---")):
            cells = [c.strip() for c in line.strip().strip("|").split(" | ")]
            if len(cells) >= 3 and cells[2] not in {UNKNOWN, FIRST_PARTY}:
                out[(eco, cells[0], cells[1])] = cells[2]
    return out


def _sorted(deps: list[Dep], eco: str) -> list[Dep]:
    return sorted(
        (d for d in deps if d.ecosystem == eco), key=lambda d: (d.name.lower(), d.version)
    )


def _cell(text: str) -> str:
    return text.replace("|", "/")


def render_register(deps: list[Dep]) -> str:
    lines = [
        "# Dependency licence register",
        "",
        "<!-- GENERATED by scripts/licenses_report.py from uv.lock and pnpm-lock.yaml. -->",
        "<!-- Do not edit. Regenerate with `python scripts/licenses_report.py`. -->",
        "",
        "Licences come from locally installed metadata only (uv venv dist-info and",
        "`node_modules/.pnpm` package.json); nothing is fetched or guessed. `UNKNOWN` fails CI.",
        "Policy: permissive passes; MPL-2.0 passes dev-only; copyleft, non-commercial and EULA",
        "fail unless allowlisted with a reason (ADR-0002, PRP-00 Clarification 10).",
        "",
        "## Allowlist",
        "",
    ]
    if ALLOWLIST:
        lines += ["| Package | Reason |", "| --- | --- |"]
        lines += [f"| {n} | {_cell(r)} |" for n, r in sorted(ALLOWLIST.items())]
    else:
        lines.append("None. No dependency needs an exception.")
    lines += ["", "Always denied: " + ", ".join(f"`{p}` ({r})" for p, r in DENYLIST.items()), ""]
    for eco, title, src in (
        ("python", "Python", "uv.lock"),
        ("npm", "npm", "pnpm-lock.yaml"),
    ):
        rows = _sorted(deps, eco)
        lines += [
            f"## {title} ({src}) - {len(rows)} packages",
            "",
            "| Package | Version | Licence | Scope | Support note |",
            "| --- | --- | --- | --- | --- |",
        ]
        lines += [
            f"| {d.name} | {d.version} | {_cell(d.licence)} | {d.scope} | {_cell(d.note)} |"
            for d in rows
        ]
        lines.append("")
    return "\n".join(lines)


def _source_url(d: Dep) -> str:
    if d.ecosystem == "python":
        return f"https://pypi.org/project/{_pep503(d.name)}/"
    return f"https://www.npmjs.com/package/{d.name}"


def render_adr_block(deps: list[Dep]) -> str:
    lines = [BEGIN, ""]
    for eco, title in (("python", "Python (uv.lock)"), ("npm", "npm (pnpm-lock.yaml)")):
        rows = _sorted(deps, eco)
        lines += [
            f"#### {title}: {len(rows)} packages",
            "",
            "| Component | Pin | Licence | Source | Note |",
            "|---|---|---|---|---|",
        ]
        for d in rows:
            src = "workspace" if d.licence == FIRST_PARTY else _source_url(d)
            note = d.scope if d.licence == FIRST_PARTY else f"{d.scope}; {d.note}"
            lines.append(f"| {d.name} | {d.version} | {_cell(d.licence)} | {src} | {_cell(note)} |")
        lines.append("")
    lines.append(END)
    return "\n".join(lines)


def splice_adr(adr_text: str, block: str) -> str:
    """Replace the generated block in the ADR; fail loudly if the markers are missing."""
    start, stop = adr_text.find(BEGIN), adr_text.find(END)
    if start == -1 or stop == -1 or stop < start:
        raise ValueError("ADR-0002 is missing the licences-register markers")
    return adr_text[:start] + block + adr_text[stop + len(END) :]


# --- entry point ------------------------------------------------------------------------


def _norm(text: str) -> str:
    return text.replace("\r\n", "\n").rstrip("\n") + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawTextHelpFormatter)
    ap.add_argument("--check", action="store_true", help="fail on diff or policy violation")
    ap.add_argument("--uv-lock", type=Path, default=ROOT / "uv.lock")
    ap.add_argument("--pnpm-lock", type=Path, default=ROOT / "pnpm-lock.yaml")
    ap.add_argument("--venv", type=Path, default=ROOT / ".venv")
    ap.add_argument("--node-modules", type=Path, default=ROOT / "node_modules")
    ap.add_argument("--output", type=Path, default=ROOT / "docs" / "licenses.md")
    ap.add_argument("--adr", type=Path, default=ADR_PATH)
    args = ap.parse_args(argv)

    carried: dict[tuple[str, str, str], str] = {}
    if args.output.is_file():
        carried = parse_register(args.output.read_text(encoding="utf-8"))

    deps: list[Dep] = []
    if args.uv_lock.is_file():
        deps += read_uv_lock(args.uv_lock, find_site_packages(args.venv), carried)
    if args.pnpm_lock.is_file():
        deps += read_pnpm_lock(args.pnpm_lock, args.node_modules / ".pnpm", carried)

    problems = [f"{d.ecosystem}:{d.name}@{d.version}: {w}" for d in deps if (w := violation(d))]
    register = _norm(render_register(deps))
    adr_new = None
    if args.adr.is_file():
        adr_new = _norm(splice_adr(args.adr.read_text(encoding="utf-8"), render_adr_block(deps)))

    if args.check:
        current = _norm(args.output.read_text(encoding="utf-8")) if args.output.is_file() else ""
        if current != register:
            problems.append(f"{args.output.name} is stale: run python scripts/licenses_report.py")
        if adr_new is not None and _norm(args.adr.read_text(encoding="utf-8")) != adr_new:
            problems.append(
                f"{args.adr.name} appendix is stale: run python scripts/licenses_report.py"
            )
    else:
        args.output.write_text(register, encoding="utf-8", newline="\n")
        if adr_new is not None:
            args.adr.write_text(adr_new, encoding="utf-8", newline="\n")
        print(f"wrote {args.output} ({len(deps)} dependencies)")

    for p in problems:
        print(f"FAIL {p}")
    if problems:
        return 1
    print(f"PASS licences ({len(deps)} dependencies)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
