"""Derive the PRP status table in PRPs/PRP-MASTER-neurosphere.md from the filesystem.

The directory a PRP file lives in is the source of truth:
    PRPs/backlog/  -> backlog
    PRPs/active/   -> active
    PRPs/shipped/  -> shipped
/prp:prp-execute moves the file; this script regenerates the table between the
`<!-- prp-status:begin -->` and `<!-- prp-status:end -->` markers. "Ready" means
every PRP dependency is shipped; non-PRP dependencies (live gates, budget
approval) are listed as manual gates and never auto-satisfied.

Usage:
    python scripts/prp_status.py --write   # regenerate the table in place
    python scripts/prp_status.py --check   # exit 1 if the table is stale
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass, field
from datetime import date
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")  # type: ignore[union-attr]

ROOT = Path(__file__).resolve().parents[1]
PRPS = ROOT / "PRPs"
MASTER = PRPS / "PRP-MASTER-neurosphere.md"
BEGIN = "<!-- prp-status:begin -->"
END = "<!-- prp-status:end -->"
STATES = ("backlog", "active", "shipped")
FILE_RE = re.compile(r"^PRP-(\d{2})-([a-z0-9-]+)\.md$")
PRP_REF_RE = re.compile(r"\bPRP-(\d{2})\b")


@dataclass
class Prp:
    pid: str
    slug: str
    state: str
    path: Path
    wave: str = ""
    model: str = ""
    review: str = ""
    frontmatter_status: str = ""
    depends: list[str] = field(default_factory=list)
    manual_gates: list[str] = field(default_factory=list)


def frontmatter(text: str) -> dict[str, str]:
    if not text.startswith("---"):
        return {}
    end = text.find("\n---", 3)
    if end == -1:
        return {}
    out: dict[str, str] = {}
    for line in text[3:end].splitlines():
        if ":" in line and not line.startswith(" "):
            key, _, value = line.partition(":")
            out[key.strip()] = value.split("#", 1)[0].strip()
    return out


def parse_depends(raw: str) -> tuple[list[str], list[str]]:
    ids = PRP_REF_RE.findall(raw)
    rest = PRP_REF_RE.sub("", raw)
    manual = [
        token.strip(" +")
        for token in re.split(r"[,+;]", rest)
        if token.strip(" +") and token.strip(" +").lower() != "none"
    ]
    return ids, manual


def scan() -> dict[str, Prp]:
    prps: dict[str, Prp] = {}
    for state in STATES:
        for path in sorted((PRPS / state).glob("PRP-*.md")):
            m = FILE_RE.match(path.name)
            if not m:
                continue
            fm = frontmatter(path.read_text(encoding="utf-8"))
            ids, manual = parse_depends(fm.get("depends_on", ""))
            prp = Prp(
                pid=m.group(1),
                slug=m.group(2),
                state=state,
                path=path,
                wave=fm.get("wave", ""),
                model=fm.get("model", ""),
                review=fm.get("review", ""),
                frontmatter_status=fm.get("status", ""),
                depends=ids,
                manual_gates=manual,
            )
            if prp.pid in prps:
                other = prps[prp.pid].path
                raise SystemExit(f"PRP-{prp.pid} exists in two directories: {other} and {path}")
            prps[prp.pid] = prp
    return prps


def render(prps: dict[str, Prp]) -> str:
    counts = {s: sum(1 for p in prps.values() if p.state == s) for s in STATES}
    start_here = next(
        (
            p
            for p in sorted(prps.values(), key=lambda x: (x.wave, x.pid))
            if p.state == "backlog"
            and all(prps.get(d, Prp("", "", "", Path())).state == "shipped" for d in p.depends)
        ),
        None,
    )
    if start_here:
        next_line = (
            f"**Next ready: PRP-{start_here.pid} {start_here.slug}** (wave {start_here.wave})."
        )
    else:
        next_line = "No backlog PRP is ready; check manual gates."
    lines = [
        BEGIN,
        f"_Generated by `python scripts/prp_status.py --write` on {date.today().isoformat()}; "
        "do not edit by hand. The directory each file sits in is the status._",
        "",
        f"Shipped {counts['shipped']} · Active {counts['active']} · Backlog {counts['backlog']} "
        f"of {len(prps)}. {next_line}",
        "",
        "| PRP | Status | Wave | Depends on | Ready | Model | Review | Note |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for p in sorted(prps.values(), key=lambda x: x.pid):
        unmet = [d for d in p.depends if prps.get(d, Prp("", "", "", Path())).state != "shipped"]
        if p.state == "shipped":
            ready = "done"
        elif p.state == "active":
            ready = "in progress"
        elif unmet:
            ready = "blocked by " + ", ".join(f"PRP-{d}" for d in unmet)
        elif p.manual_gates:
            ready = "manual gate"
        else:
            ready = "**yes**"
        notes = []
        if p.manual_gates:
            notes.append("manual: " + "; ".join(p.manual_gates))
        if p.frontmatter_status and p.frontmatter_status != p.state:
            notes.append(f"frontmatter says `{p.frontmatter_status}`, fix it")
        if start_here and p.pid == start_here.pid:
            notes.insert(0, "START HERE")
        deps = ", ".join(f"PRP-{d}" for d in p.depends) or "none"
        link = f"[PRP-{p.pid}]({p.state}/{p.path.name})"
        cells = [
            f"{link} {p.slug}",
            p.state,
            p.wave,
            deps,
            ready,
            p.model,
            p.review,
            "; ".join(notes),
        ]
        lines.append("| " + " | ".join(cells) + " |")
    lines.append(END)
    return "\n".join(lines)


def splice(text: str, block: str) -> str:
    begin = text.find(BEGIN)
    end = text.find(END)
    if begin == -1 or end == -1 or end < begin:
        raise SystemExit(f"{MASTER.relative_to(ROOT)} lacks the {BEGIN} / {END} markers")
    return text[:begin] + block + text[end + len(END) :]


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="regenerate the table in place")
    mode.add_argument("--check", action="store_true", help="exit 1 if the table is stale")
    args = parser.parse_args()

    prps = scan()
    if not prps:
        print("no PRP files found under PRPs/{backlog,active,shipped}")
        return 1
    current = MASTER.read_text(encoding="utf-8")
    block = render(prps)
    updated = splice(current, block)

    # Compare without the generated-on date so a check does not go stale overnight.
    def strip_date(s: str) -> str:
        return re.sub(r"on \d{4}-\d{2}-\d{2};", "on <date>;", s)

    if args.check:
        if strip_date(updated) != strip_date(current):
            print(
                "STALE: PRP status table does not match PRPs/ directories. "
                "Run: python scripts/prp_status.py --write"
            )
            return 1
        print(f"OK: PRP status table current ({len(prps)} PRPs)")
        return 0
    if updated != current:
        MASTER.write_text(updated, encoding="utf-8")
        print(f"updated {MASTER.relative_to(ROOT)} ({len(prps)} PRPs)")
    else:
        print("no change")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
